### ISSUE TITLE
Create a loading component

### ISSUE THREAD

**Issue by pandurijal** [pandurijal/loremi#1]
## Description
The user doesn't know when the app is still fetching a new lorem-ipsum data, because there is no loading indicator. So, create one!

## Expectation
Create a new loading component and implement it on the code when the app fetching new data. Just as simple as `Loading...` word is okay, but still, I expect this is created on a new separated component.

**Comment by peakercope** [comment]
hey, @pandurijal 
I can do that

**Comment by pandurijal** [comment]
Okay, @peakercope take this issue!
